build:
  image: node:5.0.0
  commands:
    - apt-get -qq update
    - apt-get -qq install sqlite3
    - sqlite3 -init test/data.sql /drone/test.db
    - npm install
    - npm test

publish:
  docker:
    username: cushy79
    password: $$DOCKERHUB_PASS
    email: cushy79@gmail.com
    repo: cushy79/node
    tag: $$BRANCH
    storage_driver: vfs
  ecr:
    region: ap-northeast-1
    repo: node
    tag: latest
    file: Dockerfile

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: tmp
    username: drone
    template: >
      build #{{ build.number }} finished with a {{ build.status }} status
